const PORTFOLIO = [
  {
    title: 'Lolita',
    blurredIndex: require('images/portfolio_index/lolita.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'lolita'
  },
  {
    title: 'Eyes',
    blurredIndex: require('images/portfolio_index/eyes.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'eyes'
  },
  {
    title: 'Knit Parade',
    blurredIndex: require('images/portfolio_index/knit_parade.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'knit-parade'
  },
  {
    title: 'Fat Guy',
    blurredIndex: require('images/portfolio_index/fatguy.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'fat-guy'
  },
  {
    title: 'Knit Grid',
    blurredIndex: require('images/portfolio_index/knitgrid.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'knit-grid'
  },
  {
    title: 'Circuits',
    blurredIndex: require('images/portfolio_index/circuits.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'circuits'
  },
  {
    title: 'Cats',
    blurredIndex: require('images/portfolio_index/cats.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'cats'
  },
  {
    title: 'Landscape',
    blurredIndex: require('images/portfolio_index/landscape.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'landscape'
  },
  {
    title: 'Knit Paint',
    blurredIndex: require('images/portfolio_index/knitpaint.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'knit-paint'
  },
  {
    title: 'Drawer 1',
    blurredIndex: require('images/portfolio_index/drawer1.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'drawer-1'
  },
  {
    title: 'Screenprint',
    blurredIndex: require('images/portfolio_index/screenprint.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'screenprint'
  },
  {
    title: 'Brain Moth',
    blurredIndex: require('images/portfolio_index/brainmoth_focus.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'brain-moth'
  },
  {
    title: 'Stones',
    blurredIndex: require('images/portfolio_index/stones.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: ''
  },
  {
    title: 'Skull',
    blurredIndex: require('images/portfolio_index/skull.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'skull'
  },
  {
    title: 'Parade',
    blurredIndex: require('images/portfolio_index/parade.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'parade'
  },
  {
    title: 'Huppah',
    blurredIndex: require('images/portfolio_index/huppah.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'huppah'
  },
  {
    title: 'Sketch',
    blurredIndex: require('images/portfolio_index/sketch.png'),
    indexAltText: '',
    inFocusIndex: '',
    large: '',
    year: null,
    description: '',
    tags: [],
    medium: '',
    size: '',
    slug: 'sketch'
  }
];

export default PORTFOLIO;
