const PORTFOLIO = [
  {
    title: 'Lolita',
    blurredIndex: require('Images/portfolio_index/lolita.png'),
    indexAltText: 'Detail of Lolita, Oil painting',
    inFocusIndex: '',
    largeAsset: '',
    year: '2007',
    description: '',
    tags: ['oil', 'painting'],
    medium: 'Oil on panel',
    categories: ['PAINTING', '2D'],
    size: '',
    slug: 'lolita'
  },
  {
    title: 'Eyes',
    blurredIndex: require('Images/portfolio_index/eyes.png'),
    indexAltText: 'Detail of Eyes, Digital Repeat',
    inFocusIndex: require('Images/portfolio_index/eyes_focus.png'),
    largeAsset: '',
    year: '2008',
    description: '',
    tags: [],
    medium: 'Digital repeat produced in Adobe Illustrator / U4ia',
    categories: ['DIGITAL REPEAT', '2D'],
    size: '',
    slug: 'eyes'
  },
  {
    title: 'Knit Parade',
    blurredIndex: require('Images/portfolio_index/knit_parade.png'),
    indexAltText: 'Detail of Knit Parade, Digital Repeat',
    inFocusIndex: require('Images/portfolio_index/knit_parade_focus.png'),
    largeAsset: '',
    year: '2008',
    description: '',
    tags: [],
    medium: 'Digital repeat produced in U4ia',
    categories: ['TEXTILES', 'DIGITAL REPEAT'],
    size: '',
    slug: 'knit-parade'
  },
  {
    title: 'Study in Pleats',
    blurredIndex: require('Images/portfolio_index/fatguy.png'),
    indexAltText: 'Detail of Pleats Study, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/fatguy_focus.png'),
    largeAsset: '',
    year: '2006',
    description: '',
    tags: [],
    medium: '',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '',
    slug: 'fat-guy'
  },
  {
    title: 'Knit Grid',
    blurredIndex: require('Images/portfolio_index/knitgrid.png'),
    indexAltText: 'Detail of Knit Grid, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/knitgrid_focus.png'),
    largeAsset: '',
    year: '2007',
    description: '',
    tags: [],
    medium: '',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '',
    slug: 'knit-grid'
  },
  {
    title: 'Circuits',
    blurredIndex: require('Images/portfolio_index/circuits.png'),
    indexAltText: 'Detail of Circuits Machine Knit',
    inFocusIndex: require('Images/portfolio_index/circuits_focus.png'),
    largeAsset: '',
    year: '2006',
    description: '',
    tags: [],
    medium: '',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '',
    slug: 'circuits'
  },
  {
    title: 'Cats',
    blurredIndex: require('Images/portfolio_index/cats.png'),
    indexAltText: 'Detail of Cats, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/cats_focus.png'),
    largeAsset: '',
    year: '2006',
    description: '',
    tags: [],
    medium: '',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '',
    slug: 'cats'
  },
  {
    title: 'Landscape',
    blurredIndex: require('Images/portfolio_index/landscape.png'),
    indexAltText: 'Detail of Landscape, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/landscape_focus.png'),
    largeAsset: '',
    year: '2007',
    description: '',
    tags: [],
    medium: '',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '',
    slug: 'landscape'
  },
  {
    title: 'Knit Paint',
    blurredIndex: require('Images/portfolio_index/knitpaint.png'),
    indexAltText: 'Detail of Knit Paint, Oil Painting',
    inFocusIndex: require('Images/portfolio_index/knitpaint_focus.png'),
    largeAsset: '',
    year: '2007',
    description: '',
    tags: [],
    medium: '',
    categories: ['PAINTING', '2D'],
    size: '',
    slug: 'knit-paint'
  },
  {
    title: 'Drawer 1',
    blurredIndex: require('Images/portfolio_index/drawer1.png'),
    indexAltText: 'Detail of Found Object Still Life, Guoache',
    inFocusIndex: require('Images/portfolio_index/drawer1_focus.png'),
    largeAsset: '',
    year: '2006',
    description: '',
    tags: [],
    medium: '',
    categories: ['PAINTING', '2D'],
    size: '',
    slug: 'drawer-1'
  },
  {
    title: 'Scene from the Woods',
    blurredIndex: require('Images/portfolio_index/screenprint.png'),
    indexAltText: 'Detail of Scene from The Woods, Screenprint',
    inFocusIndex: require('Images/portfolio_index/screenprint_focus.png'),
    largeAsset: '',
    year: '2007',
    description: '',
    tags: [],
    medium: '',
    categories: ['SCREENPRINTING', '2D'],
    size: '',
    slug: 'screenprint'
  },
  {
    title: 'Brain Moth',
    blurredIndex: require('Images/portfolio_index/brainmoth.png'),
    indexAltText: 'Detail of Abstract Brain-like Pattern, Digital Repeat',
    inFocusIndex: require('Images/portfolio_index/brainmoth_focus.png'),
    largeAsset: '',
    year: '2009',
    description: '',
    tags: [],
    medium: '',
    categories: ['DIGITAL REPEAT', '2D'],
    size: '',
    slug: 'brain-moth'
  },
  {
    title: 'Collected Stones',
    blurredIndex: require('Images/portfolio_index/stones.png'),
    indexAltText: 'Detail of Painting of Collected Stones, Guoache',
    inFocusIndex: require('Images/portfolio_index/stones_focus.png'),
    largeAsset: '',
    year: '2006',
    description: '',
    tags: [],
    medium: '',
    categories: ['PAINTING', '2D'],
    size: '',
    slug: ''
  },
  {
    title: 'Balloon Skull Installation',
    blurredIndex: require('Images/portfolio_index/skull.png'),
    indexAltText: 'Detail of Balloon Skull Installation, Mixed Media Installation',
    inFocusIndex: require('Images/portfolio_index/skull_focus.png'),
    largeAsset: '',
    year: '2015',
    description: '',
    tags: [],
    medium: '',
    categories: ['INSTALLATION', '3D'],
    size: '',
    slug: 'skull'
  },
  {
    title: 'Parade',
    blurredIndex: require('Images/portfolio_index/parade.png'),
    indexAltText: 'Detail of Parade, Digital Repeat',
    inFocusIndex: require('Images/portfolio_index/parade_focus.png'),
    largeAsset: '',
    year: '2008',
    description: '',
    tags: [],
    medium: '',
    categories: ['DIGITAL REPEAT', '2D'],
    size: '',
    slug: 'parade'
  },
  {
    title: 'Huppah',
    blurredIndex: require('Images/portfolio_index/huppah.png'),
    indexAltText: 'Detail of Huppah, Machine Knit & Wood Structure',
    inFocusIndex: require('Images/portfolio_index/huppah_focus.png'),
    largeAsset: '',
    year: '2014',
    description: '',
    tags: [],
    medium: '',
    categories: ['TEXTILES', 'INSTALLATION', '3D', 'MACHINE KNIT'],
    size: '',
    slug: 'huppah'
  },
  {
    title: 'Sketchbook',
    blurredIndex: require('Images/portfolio_index/sketch.png'),
    indexAltText: 'Detail from sketchbook, Mixed Media Collage',
    inFocusIndex: require('Images/portfolio_index/sketch_focus.png'),
    largeAsset: '',
    year: '2014',
    description: '',
    tags: [],
    medium: '',
    categories: ['SKETCHBOOK', '2D'],
    size: '',
    slug: 'sketchbook'
  }
];

export default PORTFOLIO;
