import HUPPAH from 'Config/portfolio_data/huppah';
import SKETCHBOOK from 'Config/portfolio_data/sketchbook';
import PARADE from 'Config/portfolio_data/parade';
import EYES from 'Config/portfolio_data/eyes';
import KNIT_PARADE from 'Config/portfolio_data/knit_parade';

const PORTFOLIO = [
  EYES,
  KNIT_PARADE,
  {
    title: 'Study in Pleats',
    blurredIndex: require('Images/portfolio_index/fatguy.png'),
    indexAltText: 'Detail of Pleats Study, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/fatguy_focus.png'),
    largeAsset: require('Images/show/fatman.png'),
    additionalImages: [],
    year: '2006',
    description: '',
    tags: [],
    medium: 'Machine Knit',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '8in x 8in',
    slug: 'fat-guy'
  },
  {
    title: 'Knit Grid',
    blurredIndex: require('Images/portfolio_index/knitgrid.png'),
    indexAltText: 'Detail of Knit Grid, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/knitgrid_focus.png'),
    largeAsset: require('Images/show/knitgrid.png'),
    additionalImages: [],
    year: '2007',
    description: '',
    tags: [],
    medium: 'Machine Knit panel',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '3ft x 3ft',
    slug: 'knit-grid'
  },
  {
    title: 'Circuits',
    blurredIndex: require('Images/portfolio_index/circuits.png'),
    indexAltText: 'Detail of Circuits Machine Knit',
    inFocusIndex: require('Images/portfolio_index/circuits_focus.png'),
    largeAsset: require('Images/show/circuits.png'),
    additionalImages: [],
    year: '2006',
    description: '',
    tags: [],
    medium: 'Machine knit',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '8in x 8in',
    slug: 'circuits'
  },
  {
    title: 'Cats',
    blurredIndex: require('Images/portfolio_index/cats.png'),
    indexAltText: 'Detail of Cats, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/cats_focus.png'),
    largeAsset: require('Images/show/cats.png'),
    additionalImages: [],
    year: '2006',
    description: 'Machine knit',
    tags: [],
    medium: 'Machine Knit',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '8in x 10in',
    slug: 'cats'
  },
  {
    title: 'Landscape',
    blurredIndex: require('Images/portfolio_index/landscape.png'),
    indexAltText: 'Detail of Landscape, Machine Knit',
    inFocusIndex: require('Images/portfolio_index/landscape_focus.png'),
    largeAsset: require('Images/show/landscape.png'),
    additionalImages: [],
    year: '2007',
    description: '',
    tags: [],
    medium: 'Machine Knit panel',
    categories: ['MACHINE KNIT', 'TEXTILES'],
    size: '2.5ft x 6ft',
    slug: 'landscape'
  },
  {
    title: 'Knit Paint',
    blurredIndex: require('Images/portfolio_index/knitpaint.png'),
    indexAltText: 'Detail of Knit Paint, Oil Painting',
    inFocusIndex: require('Images/portfolio_index/knitpaint_focus.png'),
    largeAsset: require('Images/show/knitpaint.png'),
    additionalImages: [],
    year: '2007',
    description: '',
    tags: [],
    medium: 'Oil paint on panel',
    categories: ['PAINTING', '2D'],
    size: '3ft x 5ft',
    slug: 'knit-paint'
  },
  {
    title: 'Drawer of Found Objects',
    blurredIndex: require('Images/portfolio_index/drawer1.png'),
    indexAltText: 'Detail of Found Object Still Life, Guoache',
    inFocusIndex: require('Images/portfolio_index/drawer1_focus.png'),
    largeAsset: require('Images/show/drawer1.png'),
    additionalImages: [],
    year: '2006',
    description: '',
    tags: [],
    medium: 'Guoache on paper',
    categories: ['PAINTING', '2D'],
    size: '8in x 10in',
    slug: 'drawer-1'
  },
  {
    title: 'Scene from the Woods',
    blurredIndex: require('Images/portfolio_index/screenprint.png'),
    indexAltText: 'Detail of Scene from The Woods, Screenprint',
    inFocusIndex: require('Images/portfolio_index/screenprint_focus.png'),
    largeAsset: require('Images/show/screenprint.png'),
    additionalImages: [],
    year: '2007',
    description: '',
    tags: [],
    medium: 'Screenprint, gold ink on paper',
    categories: ['SCREENPRINTING', '2D'],
    size: '22in x 30in',
    slug: 'screenprint'
  },
  {
    title: 'Brain Moth',
    blurredIndex: require('Images/portfolio_index/brainmoth.png'),
    indexAltText: 'Detail of Abstract Brain-like Pattern, Digital Repeat',
    inFocusIndex: require('Images/portfolio_index/brainmoth_focus.png'),
    largeAsset: require('Images/show/brainmoth.png'),
    additionalImages: [],
    year: '2009',
    description: '',
    tags: [],
    medium: '',
    categories: ['DIGITAL REPEAT', '2D'],
    size: '',
    slug: 'brain-moth'
  },
  {
    title: 'Collected Stones',
    blurredIndex: require('Images/portfolio_index/stones.png'),
    indexAltText: 'Detail of Painting of Collected Stones, Guoache',
    inFocusIndex: require('Images/portfolio_index/stones_focus.png'),
    largeAsset: require('Images/show/stones.png'),
    additionalImages: [],
    year: '2006',
    description: '',
    tags: [],
    medium: 'Guoache on paper',
    categories: ['PAINTING', '2D'],
    size: '6in x 7in',
    slug: 'stones'
  },
  {
    title: 'Balloon Skull Installation',
    blurredIndex: require('Images/portfolio_index/skull.png'),
    indexAltText: 'Detail of Balloon Skull Installation, Mixed Media Installation',
    inFocusIndex: require('Images/portfolio_index/skull_focus.png'),
    largeAsset: require('Images/show/skull.jpg'),
    additionalImages: [],
    year: '2015',
    description: '',
    tags: ['installation'],
    medium: 'Balloons, mixed media',
    categories: ['INSTALLATION', '3D'],
    size: '12ft x 12ft',
    slug: 'skull'
  },
  {
    title: 'Lolita',
    blurredIndex: require('Images/portfolio_index/lolita.png'),
    indexAltText: 'Detail of Lolita, Oil painting',
    inFocusIndex: '',
    largeAsset: require('Images/show/lolita.png'),
    additionalImages: [],
    year: '2007',
    description: '',
    tags: ['oil', 'painting'],
    medium: 'Oil on linen',
    categories: ['PAINTING', '2D'],
    size: '11in x 14in',
    slug: 'lolita'
  },
  PARADE,
  HUPPAH,
  SKETCHBOOK
];

export default PORTFOLIO;
